name: CI Build

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          6.0.x
    
    - name: Build Meadow.Foundatation.mikroBUS
      run: dotnet build -c Release Source/mikroBUS.sln
