name: Package Creation

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]"

env:
  token: ${{ secrets.NUGET_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from env.version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      
    - uses: ./.github/actions/build-package
      with:
        packageId: Meadow.Foundation.mikroBUS.Displays.C16x9
        path: Source/C16x9/Driver/C16x9.csproj
        version: ${VERSION}
        token: ${{ env.token }}

    - uses: ./.github/actions/build-package
      with:
        packageId: Meadow.Foundation.mikroBUS.Displays.C8800Retro
        path: Source/C8800Retro/Driver/C8800Retro.csproj
        version: ${VERSION}
        token: ${{ env.token }}

    - uses: ./.github/actions/build-package
      with:
        packageId: Meadow.Foundation.mikroBUS.Displays.C8x8
        path: Source/C8x8/Driver/C8x8.csproj
        version: ${VERSION}
        token: ${{ env.token }}

    - uses: ./.github/actions/build-package
      with:
        packageId: Meadow.Foundation.mikroBUS.Sensors.Buttons.CButton
        path: Source/CButton/Driver/CButton.csproj
        version: ${VERSION}
        token: ${{ env.token }}

    - uses: ./.github/actions/build-package
      with:
        packageId: Meadow.Foundation.mikroBUS.Sensors.Hid.CJoystick
        path: Source/CJoystick/Driver/CJoystick.csproj
        version: ${VERSION}
        token: ${{ env.token }}
        
    - uses: ./.github/actions/build-package
      with:
        packageId: Meadow.Foundation.mikroBUS.Sensors.Gnss.CGNSS10
        path: Source/CGNSS10/Driver/CGNSS10.csproj
        version: ${VERSION}
        token: ${{ env.token }}

    - uses: ./.github/actions/build-package
      with:
        packageId: Meadow.Foundation.mikroBUS.Sensors.Atmospheric.CTempHum15
        path: Source/CTempHum15/Driver/CTempHum15.csproj
        version: ${VERSION}
        token: ${{ env.token }}


